import { Song } from './types';

export const MOCK_SONGS: Song[] = [
  // 전례곡 (1-53)
  {
    id: '1',
    number: 1,
    title: '참회예절문',
    category: '전례곡',
    usage: '참회',
    tags: ['참회'],
    sheets: ['/sheets/1.참회예절도문.png'],
    audioUrl: '/audio/1.참회예절문.mp3',
  },
  {
    id: '2',
    number: 2,
    title: '감사송 - 참회예절',
    category: '전례곡',
    usage: '참회',
    tags: ['참회', '감사'],
    sheets: ['/sheets/2.참회예절 감사송.png'],
    audioUrl: '/audio/2.감사송 - 참회예절.mp3',
  },
  {
    id: '3',
    number: 3,
    title: '대영광송',
    category: '전례곡',
    usage: '대영광송',
    tags: ['찬양'],
    sheets: ['/sheets/3.대영광송.png'],
    audioUrl: '/audio/3.대영광송.mp3',
  },
  {
    id: '4-1',
    number: 4,
    title: '거룩하시도다 - 연중',
    category: '전례곡',
    usage: '성찬',
    tags: ['찬양'],
    sheets: ['/sheets/4.거룩하시도다 연중.png'],
    audioUrl: '/audio/4-1.거룩하시도다 - 연중.mp3',
  },
  {
    id: '4-2',
    number: 4,
    title: '거룩하시도다 - 1988',
    category: '전례곡',
    usage: '성찬',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '5-1',
    number: 5,
    title: '거룩하시도다 - 대림',
    category: '전례곡',
    usage: '성찬',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '5-2',
    number: 5,
    title: '거룩하시도다 - 부활',
    category: '전례곡',
    usage: '성찬',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '6',
    number: 6,
    title: '거룩하시도다 - 사순',
    category: '전례곡',
    usage: '성찬',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '7',
    number: 7,
    title: '감사송 - 성찬기도 2양식',
    category: '전례곡',
    usage: '성찬',
    tags: ['감사'],
    sheets: [],
  },
  {
    id: '20-1',
    number: 20,
    title: '신자들의 기도 I',
    category: '전례곡',
    usage: '성찬',
    tags: ['기도'],
    sheets: [],
  },
  {
    id: '20-2',
    number: 20,
    title: '신자들의 기도 II',
    category: '전례곡',
    usage: '성찬',
    tags: ['기도'],
    sheets: [],
  },
  {
    id: '21',
    number: 21,
    title: '하느님의 어린양',
    category: '전례곡',
    usage: '영성체',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '23',
    number: 23,
    title: '거룩하시도다 거룩하신 주',
    category: '전례곡',
    usage: '성찬',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '31',
    number: 31,
    title: '부활하셨네',
    category: '부활',
    usage: '환호',
    tags: ['기쁨'],
    sheets: [],
  },
  {
    id: '32',
    number: 32,
    title: '깊은 구렁 속에서 부르짖사오니 (시130)',
    category: '구약',
    usage: '입당',
    tags: ['참회'],
    sheets: [],
  },
  {
    id: '33',
    number: 33,
    title: '내 영혼아 야훼님 찬미하라 (시 103)',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '34',
    number: 34,
    title: '야훼 나의 하느님',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '35',
    number: 35,
    title: '부르짖는 이 소리 주께 이르게하사',
    category: '구약',
    usage: '입당',
    tags: ['기도'],
    sheets: [],
  },
  {
    id: '36',
    number: 36,
    title: '좋기도 좋을시고 I (시 133)',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '37',
    number: 37,
    title: '좋기도 좋을시고 II (시 133)',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '38',
    number: 38,
    title: '주님께 감사 (시 136)',
    category: '구약',
    usage: '입당',
    tags: ['감사'],
    sheets: [],
  },
  {
    id: '39',
    number: 39,
    title: '세 청년의 노래 1부',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '40',
    number: 40,
    title: '세 청년의 노래 2부',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '41',
    number: 41,
    title: '주 찬양하라 알렐루야 (시 150)',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '42',
    number: 42,
    title: '에베누 샬롬 알레헴',
    category: '기타',
    usage: '입당',
    tags: ['평화'],
    sheets: [],
  },
  {
    id: '43',
    number: 43,
    title: '주님의 나라가 왔도다',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '44',
    number: 44,
    title: '누가 떼어 놓으랴',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '45',
    number: 45,
    title: '마니피깟',
    category: '마리아의 노래',
    usage: '입당',
    tags: ['성모'],
    sheets: [],
  },
  {
    id: '46',
    number: 46,
    title: '주님이 집에 데려오실 제 (시 126)',
    category: '구약',
    usage: '입당',
    tags: ['감사'],
    sheets: [],
  },
  {
    id: '47',
    number: 47,
    title: '즈가리아의 노래',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '48',
    number: 48,
    title: '승리가 죽음을 삼켰다',
    category: '부활',
    usage: '환호',
    tags: ['기쁨'],
    sheets: [],
  },
  {
    id: '49',
    number: 49,
    title: '아브라함',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '50',
    number: 50,
    title: '모세의 노래',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '51',
    number: 51,
    title: '주께 노래하라 (시 177)',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '52',
    number: 52,
    title: '주님은 나의 목자 (시 23)',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '53',
    number: 53,
    title: '하느님은 자비하시니 (시 50)',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },

  // 54-80
  {
    id: '54',
    number: 54,
    title: '그리스도 예수는 주님이시다',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '55',
    number: 55,
    title: '아베 마리아 - 1984',
    category: '마리아의 노래',
    usage: '성모찬송',
    tags: ['성모'],
    sheets: [],
  },
  {
    id: '56',
    number: 56,
    title: '마리아 미소한 마리아',
    category: '마리아의 노래',
    usage: '성모찬송',
    tags: ['성모'],
    sheets: [],
  },
  {
    id: '57',
    number: 57,
    title: '산들을 우러러 눈을 드노라 (시 121)',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '58',
    number: 58,
    title: '만일 오늘 주님의 목소리를 듣게 되거든',
    category: '구약',
    usage: '입당',
    tags: ['기도'],
    sheets: [],
  },
  {
    id: '59-1',
    number: 59,
    title: '다예누',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '59-2',
    number: 59,
    title: '다예누',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '61',
    number: 61,
    title: '빠스카의 제물게',
    category: '부활',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '62',
    number: 62,
    title: '우리 우리 우리 우라',
    category: '기타',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '63',
    number: 63,
    title: '하늘에서 별 하나를 보았기 때문에',
    category: '성탄',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '64',
    number: 64,
    title: '주님이 집을 짓지 않으시면 (시 127)',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '65',
    number: 65,
    title: '내 형제들의 사랑을 위해 (시 122)',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '66',
    number: 66,
    title: '주님을 기다리고 기다렸더니 (시 40)',
    category: '구약',
    usage: '입당',
    tags: ['기도'],
    sheets: [],
  },
  {
    id: '67',
    number: 67,
    title: '당신께 노래하리라 (시 57)',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '68',
    number: 68,
    title: '하느님을 기다려라 (시 42, 43)',
    category: '구약',
    usage: '입당',
    tags: ['기도'],
    sheets: [],
  },
  {
    id: '69',
    number: 69,
    title: '주님께 소리쳐라 (시 100)',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '70',
    number: 70,
    title: '기쁨으로 소리쳐라',
    category: '구약',
    usage: '입당',
    tags: ['기쁨'],
    sheets: [],
  },
  {
    id: '71',
    number: 71,
    title: '나 깨어나 네 얼굴로 흐뭇하리다 주님 (시 17)',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '72',
    number: 72,
    title: '왜 오늘 밤은 들리나요',
    category: '기타',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '73',
    number: 73,
    title: '주 찬양하라 예루살렘 (시 147)',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '74',
    number: 74,
    title: '말하여라 마음이 지친 이들에게',
    category: '구약',
    usage: '입당',
    tags: ['위로'],
    sheets: [],
  },
  {
    id: '75',
    number: 75,
    title: '환호소리 또 나팔소리 속에 (시 47)',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '76',
    number: 76,
    title: '어둠 속을 걷던 백성들이',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '77',
    number: 77,
    title: '발람',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '78',
    number: 78,
    title: '천사들 앞에서 (시 138)',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '79',
    number: 79,
    title: '계시는 곳 얼마나 좋으신가 (시 84)',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '80',
    number: 80,
    title: '위엄을 입고 여기 주님 오신다 (시 93)',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },

  // 81-107
  {
    id: '81',
    number: 81,
    title: '안식의 날',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '82',
    number: 82,
    title: '위로하여라 내 백성을',
    category: '구약',
    usage: '입당',
    tags: ['위로'],
    sheets: [],
  },
  {
    id: '108',
    number: 108,
    title: '주여 내 기도를 들어주소서 (시 143)',
    category: '구약',
    usage: '입당',
    tags: ['기도'],
    sheets: [],
  },
  {
    id: '109',
    number: 109,
    title: '어리석은 자 하느님 없다 생각하네 (시 14)',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '110',
    number: 110,
    title: '산상설교',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },

  // 신약 (201-219)
  {
    id: '201',
    number: 201,
    title: '고요히 침묵 속에 안자 있으라',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '202',
    number: 202,
    title: '임금들이 널 보고 일어서리라',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '203',
    number: 203,
    title: '야곱',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '204',
    number: 204,
    title: '데보라의 노래',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '205',
    number: 205,
    title: '주님은 나에게',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '207',
    number: 207,
    title: '씨 뿌리는 사람',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '208',
    number: 208,
    title: '주의 영이 내 위에 내리셨네 (루가 4.18-19)',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '209',
    number: 209,
    title: '주는 나를 꿰뚫어 아시네 (시 139)',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '210',
    number: 210,
    title: '엘리 엘리 라마 사박타니',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '211',
    number: 211,
    title: '엘리 엘리 라마 사박타니',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '212',
    number: 212,
    title: '누구도 두 주인을 섬길 수 없다',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '213',
    number: 213,
    title: '주여 내 마음은 더 이상 오만하지 않고 (시 131)',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '214',
    number: 214,
    title: '나는 가리라 예루살렘에 (순례자의 노래)',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '215',
    number: 215,
    title: '셰마 이스라엘',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '216',
    number: 216,
    title: '영광스러운 십자가의 찬가',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '217',
    number: 217,
    title: '하느님의 갑옷으로 무장하라',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '218',
    number: 218,
    title: '시온 모든 민족의 어머니 (시 18)',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '219',
    number: 219,
    title: '아께다',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },

  // 261-278
  {
    id: '261',
    number: 261,
    title: '같은 하느님께서',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '262',
    number: 262,
    title: '사형선고 받은 사람처럼',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '263',
    number: 263,
    title: '예수는 온 도시를 두루 다니시며',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '264',
    number: 264,
    title: '그 입술로 내게 입 맞춰주오',
    category: '기타',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '265',
    number: 265,
    title: '신부여 레바논에서 오라',
    category: '기타',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '266',
    number: 266,
    title: '나는 잠들었는데',
    category: '기타',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '267',
    number: 267,
    title: '그대 내 님이여',
    category: '기타',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '268',
    number: 268,
    title: '저 여인은 누구인가',
    category: '기타',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '269',
    number: 269,
    title: '볼품이 없다 (야훼의 종의 넷째 노래)',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '270',
    number: 270,
    title: '어린 양의 노래',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '271',
    number: 271,
    title: '내 손을 펼치고',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '272',
    number: 272,
    title: '멜라톤 데 사르데스의 부활강론 한 편',
    category: '부활',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '273',
    number: 273,
    title: '63년의 카르멘',
    category: '기타',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '274',
    number: 274,
    title: '까리따스 크리스티',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '275',
    number: 275,
    title: '주여, 도와주소서',
    category: '구약',
    usage: '입당',
    tags: ['기도'],
    sheets: [],
  },
  {
    id: '276',
    number: 276,
    title: '하늘로 나를 데려가소서',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '277',
    number: 277,
    title: '날 꾀어내셨네, 주여',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '278',
    number: 278,
    title: '어느 어두운 밤에',
    category: '기타',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },

  // 401-436
  {
    id: '401',
    number: 401,
    title: '민족들 가운데서 데려오리라',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '402',
    number: 402,
    title: '행복한 사람',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '403',
    number: 403,
    title: '사랑의 송가',
    category: '기타',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '404',
    number: 404,
    title: '홀로 그를 향해',
    category: '기타',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '405',
    number: 405,
    title: '아름답구나 내 친구야',
    category: '기타',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '406',
    number: 406,
    title: '형제들아',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '407',
    number: 407,
    title: '원수에 대한 분노의 격정처럼',
    category: '기타',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '408',
    number: 408,
    title: '큰 무리 가운데서',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '409',
    number: 409,
    title: '여기에 없다',
    category: '부활',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '410',
    number: 410,
    title: '네개의 밤 노래',
    category: '기타',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '411',
    number: 411,
    title: '오순절',
    category: '성령',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '412',
    number: 412,
    title: '예루살렘 다시 세워졌네',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '413',
    number: 413,
    title: '이것이 나의 계명이다',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '414',
    number: 414,
    title: '자캐오',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '415',
    number: 415,
    title: '그 옛날 이스라엘이 이집트를 떠날때',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '416',
    number: 416,
    title: '저 별에서 내려와',
    category: '성탄',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '417',
    number: 417,
    title: '살베 레지나',
    category: '마리아의 노래',
    usage: '성모찬송',
    tags: ['성모'],
    sheets: [],
  },
  {
    id: '418',
    number: 418,
    title: '훔쳤구나 내 마음을',
    category: '기타',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '419',
    number: 419,
    title: '하느님, 내 하느님',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '420',
    number: 420,
    title: '불멸의 비둘기',
    category: '기타',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '421',
    number: 421,
    title: '죄악의 바빌로니아 수도여(시 137)',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '422',
    number: 422,
    title: '내게로 오라 너희들 모두',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '423',
    number: 423,
    title: '큰 표징 하나',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '424',
    number: 424,
    title: '오신다 하느님',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '425',
    number: 425,
    title: '술짜는 사람',
    category: '기타',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '426',
    number: 426,
    title: '너희는 그리스도와함께 부활했으니',
    category: '부활',
    usage: '입당',
    tags: ['기쁨'],
    sheets: [],
  },
  {
    id: '427',
    number: 427,
    title: '하늘이 열리고(묵시)',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '428',
    number: 428,
    title: '문들아 어서 머리를 들어라',
    category: '구약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '429',
    number: 429,
    title: '메시아 승리하는 사자',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '430',
    number: 430,
    title: '저것 좀 봐, 물고기들이 물을 마시네',
    category: '기타',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '431',
    number: 431,
    title: '종소리 종소리 울리면',
    category: '기타',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '432',
    number: 432,
    title: 'Resurrexit(레수렉싯)',
    category: '부활',
    usage: '입당',
    tags: ['기쁨'],
    sheets: [],
  },
  {
    id: '433',
    number: 433,
    title: '나의 멍에는 편하고, 내 짐은 가볍다',
    category: '신약',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '434',
    number: 434,
    title: '기뻐하여라',
    category: '신약',
    usage: '입당',
    tags: ['기쁨'],
    sheets: [],
  },
  {
    id: '435',
    number: 435,
    title: '대림찬가',
    category: '대림',
    usage: '입당',
    tags: ['찬양'],
    sheets: [],
  },
  {
    id: '436',
    number: 436,
    title: '부르고 있나이다. 주님',
    category: '구약',
    usage: '입당',
    tags: ['기도'],
    sheets: [],
  },
];

export const CATEGORIES = {
  seasons: ['대림', '성탄', '사순', '부활', '연중', '성령'],
  usages: [
    '입당',
    '참회',
    '자비송',
    '대영광송',
    '복음환호송',
    '봉헌',
    '성찬',
    '영성체',
    '파견',
  ],
  tags: [
    '찬양',
    '감사',
    '평화',
    '참회',
    '봉헌',
    '기쁨',
    '성모',
    '성인',
    '성령',
  ],
};
